name: Continuous Integration

on:
  pull_request:
    branches: [develop, main]

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Npm version
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test coverage
        run: npm run test:cov

      - name: Build
        run: npm run build